### ISSUE TITLE
Folding issue

### ISSUE THREAD

**Issue by lunisolar** [lunisolar/LNKD.tech-Editor#2]
Jan 8, 2021 6:43:12 PM UTC
Conflicts: 0
IDE-build: IC-203.6682.168
IDE-name: IntelliJ IDEA
level: error
release: 0.8.2-EARLY_ACCESS

java.lang.AssertionError: preemptively-anonymized (was non-null)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:178)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:102)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:83)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:68)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:51)
    at tech.lnkd.editor.intellij.turtle.view.TurtleFoldingBuilder$6.<init>(TurtleFoldingBuilder.java:133)

**Comment by lunisolar** [comment]
Reproduction: 
1. declare prefix for namespace (e.g. `@prefix p1: <http://example.org/> .` )
2. declare base IRI with the same namespace (e.g. `@base <http://example.org/> .`  )
3. use relative IRI from that namespace (e.g. `<resoruce1>` )

**Comment by lunisolar** [comment]
Resolved, pending the release of 0.9

**Comment by lunisolar** [comment]
Additional report (same cause):

Jan 12, 2021 10:14:04 AM UTC
Conflicts: 0
IDE-build: IC-203.6682.168
IDE-name: IntelliJ IDEA
level: error
release: 0.8.2-EARLY_ACCESS
