### ISSUE TITLE
2021.2 - Compatibility for slow operations with 2021.2 ('assertSlowOperationsAreAllowed' @ 'tupleCount')

### ISSUE THREAD

**Issue by lunisolar** [lunisolar/LNKD.tech-Editor#22]
```
java.lang.Throwable: preemptively-anonymized (was non-null)
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
    at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:108)
  ...
    at tech.lnkd.editor.index.TripleStoreIndex.tupleCount(TripleStoreIndex.java:194)
```

**Comment by lunisolar** [comment]
The issue is only related to 2021.2 that is not yet released. 
The issue is also not critical. Although it might occur regularly report a lot.

**Comment by lunisolar** [comment]
Release pending.
