### ISSUE TITLE
Custom Global Graphs have issue with the space in file or directory name

### ISSUE THREAD

**Issue by lunisolar** [lunisolar/LNKD.tech-Editor#23]
Illegal character in path at index 36: file:/Users/......../Downloads/..... (3).ttl
operating system: MaxOS
```
java.net.URISyntaxException: preemptively-anonymized (was non-null)
    at java.net.URI$Parser.fail(URI.java:2913)
    at java.net.URI$Parser.checkChars(URI.java:3084)
    at java.net.URI$Parser.parseHierarchical(URI.java:3166)
    at java.net.URI$Parser.parse(URI.java:3114)
    at java.net.URI.<init>(URI.java:600)
    at java.net.URL.toURI(URL.java:1061)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:81)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.map(OptTrait.java:538)
    at tech.lnkd.editor.sem_web.globalGraphs.CustomGlobalGraphs.toFile(CustomGlobalGraphs.java:203)
    at tech.lnkd.editor.sem_web.globalGraphs.CustomGlobalGraphs.getFile(CustomGlobalGraphs.java:144)

```

**Comment by lunisolar** [comment]
IT looks like the space is the issue.

**Comment by lunisolar** [comment]
Release pending.
