### ISSUE TITLE
StackOverflowError in LteTurtleBlock

### ISSUE THREAD

**Issue by jak-ub** [lunisolar/LNKD.tech-Editor#34]
```
java.lang.StackOverflowError: null
    at eu.lunisolar.magma.func.supp.Clazz.assuredClass(Clazz.java:163)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at eu.lunisolar.lava.intellij.cache.IntelliJCaching$Cached.calculate(IntelliJCaching.java:175)
    at eu.lunisolar.lava.intellij.cache.IntelliJCaching$SimpleCalculation1Dep.calculate(IntelliJCaching.java:214)
    at tech.lnkd.editor.lang.turtle.elements.LteTurtleBlock.directivesAt(LteTurtleBlock.java:26)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:83)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.flatMap(OptTrait.java:1028)
    at tech.lnkd.editor.lang.turtle.elements.LteTurtleBlock.lambda$directivesAt$0(LteTurtleBlock.java:27)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:83)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.orFlatApply(OptTrait.java:1478)
    at tech.lnkd.editor.lang.turtle.elements.LteTurtleBlock.lambda$directivesAt$1(LteTurtleBlock.java:26)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:83)
    at eu.lunisolar.lava.intellij.cache.IntelliJCaching$SimpleCalculation1Dep.lambda$calculate$0(IntelliJCaching.java:214)
    at eu.lunisolar.magma.func.supplier.LSupplier.shovingGet(LSupplier.java:193)
    at eu.lunisolar.lava.intellij.cache.IntelliJCaching$CVP.compute(IntelliJCaching.java:91)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at eu.lunisolar.lava.intellij.cache.IntelliJCaching$Cached.calculate(IntelliJCaching.java:175)
    at eu.lunisolar.lava.intellij.cache.IntelliJCaching$SimpleCalculation1Dep.calculate(IntelliJCaching.java:214)
    at tech.lnkd.editor.lang.turtle.elements.LteTurtleBlock.directivesAt(LteTurtleBlock.java:26)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:83)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.flatMap(OptTrait.java:1028)
    at tech.lnkd.editor.lang.turtle.elements.LteTurtleBlock.lambda$directivesAt$0(LteTurtleBlock.java:27)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:83)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.orFlatApply(OptTrait.java:1478)
    at tech.lnkd.editor.lang.turtle.elements.LteTurtleBlock.lambda$directivesAt$1(LteTurtleBlock.java:26)

```

**Comment by jak-ub** [comment]
Can be caused by a very specific file with "errors" in directives. E.g long repeating sequence of following lines : 
```
__prefix rdf: <>
                      <resource> a "".
```

**Comment by jak-ub** [comment]
ready for release
