### ISSUE TITLE
There is no conversion from 'class org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl' 

### ISSUE THREAD

**Issue by jak-ub** [lunisolar/LNKD.tech-Editor#36]
```
java.lang.IllegalArgumentException: There is no conversion from 'class org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl' 
    at eu.lunisolar.magma.basics.exceptions.X.arg(X.java:62)
    at eu.lunisolar.magma.basics.exceptions.Handling.create(Handling.java:137)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.orElseThrow(OptTrait.java:1429)
    at eu.lunisolar.lava.data.types.conversion.ConversionMatrix.privatelyConvertIfNeeded(ConversionMatrix.java:105)
    at eu.lunisolar.lava.data.types.conversion.ConversionMatrix.convertIfNeeded(ConversionMatrix.java:71)
    at eu.lunisolar.lava.rdf.jena.data.JenaLiteral.aStr(JenaLiteral.java:172)
    at eu.lunisolar.lava.rdf.api.data.Term$Presentation.lambda$static$0(Term.java:66)
    at eu.lunisolar.magma.func.function.LFunction.apply(LFunction.java:83)
    at eu.lunisolar.lava.rdf.api.data.Term$Presentation.safeToString(Term.java:87)
    at tech.lnkd.editor.lang.turtle.inspection.shacl.ShaclInspection$Spring.lambda$table$29(ShaclInspection.java:345)
```

**Comment by jak-ub** [comment]
pending release
