### ISSUE TITLE
[JetBrains Client] java.lang.IllegalStateException: Index is not created for `KnowledgeFileIndex`

### ISSUE THREAD

**Issue by jak-ub** [lunisolar/LNKD.tech-Editor#39]
```
java.lang.IllegalStateException: Index is not created for `KnowledgeFileIndex`
    at com.intellij.util.indexing.FileBasedIndexImpl.getIndex(FileBasedIndexImpl.java:1282)
    at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:296)
    at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:249)
    at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:233)
    at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1089)
    at tech.lnkd.editor.index.IndexUtil.lambda$knowledgeFilesInScope$1(IndexUtil.java:58)
    at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:141)
    at tech.lnkd.editor.index.IndexUtil.knowledgeFilesInScope(IndexUtil.java:52)
    at tech.lnkd.editor.index.IndexUtil.stream(IndexUtil.java:46)
```

**Comment by jak-ub** [comment]
Reproduced on JetBrains Client  (part of Gateway).

JetBrains Client should not be a target for the plugin.

**Comment by jak-ub** [comment]
Closing. 
Seems like "feature" of the IntelliJ Platform: [https://github.com/JetBrains/js-graphql-intellij-plugin/issues/522](https://github.com/JetBrains/js-graphql-intellij-plugin/issues/522)
