### ISSUE TITLE
PSI: different providers 

### ISSUE THREAD

**Issue by jak-ub** [lunisolar/LNKD.tech-Editor#44]
```
om.intellij.psi.PsiInvalidElementAccessException: Element: class tech.lnkd.editor.lang.turtle.TurtleFile #turtle  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/nguyenthiphuongthao/Documents/HUST/Study/2021.2/OOP/Midterm2/Person.ttl, vFileId=203006, content=VirtualFileContent{size=0}, eventSystemEnabled=true}(441c1ed); com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/nguyenthiphuongthao/Documents/HUST/Study/2021.2/OOP/Midterm2/Person.ttl, vFileId=203006, content=VirtualFileContent{size=0}, eventSystemEnabled=true}(7812c185)
invalidated at: see attachment
    at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:476)
    at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:192)
    at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
    at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:937)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:744)
    at eu.lunisolar.lava.intellij.Psi4U.children(Psi4U.java:174)
    at eu.lunisolar.lava.intellij.Psi4U.findChildrenByClass(Psi4U.java:178)
    at tech.lnkd.editor.sem_web.search.KnowledgePsiFile.syntaxSeq(KnowledgePsiFile.java:42)
    at tech.lnkd.editor.lang.shared.elements.syntax.SyntaxTriples.lambda$populate$1(SyntaxTriples.java:23)
    at eu.lunisolar.magma.func.consumer.LBiConsumer.accept(LBiConsumer.java:81)
    at eu.lunisolar.magma.func.supp.opt.OptTrait.ifPresent(OptTrait.java:1153)
    at tech.lnkd.editor.lang.shared.elements.syntax.SyntaxTriples.populate(SyntaxTriples.java:22)
    at tech.lnkd.editor.index.Extractor.populate(Extractor.java:87)
    at tech.lnkd.editor.index.Extractor.lambda$indexByPsi$0(Extractor.java:81)
```

**Comment by jak-ub** [comment]
Might have been fixed in #41.
