### ISSUE TITLE
Indexing - FileNotFoundException - MapReduceIndex$MapInputException

### ISSUE THREAD

**Issue by lunisolar** [lunisolar/LNKD.tech-Editor#8]
```
java.io.FileNotFoundException: preemptively-anonymized (was non-null)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:219)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getInputStream(LocalFileSystemBase.java:374)
    at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getInputStream(PersistentFSImpl.java:612)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.getInputStream(VirtualFileImpl.java:110)
    at eu.lunisolar.magma.func.supplier.LSupplier.nestingGet(LSupplier.java:181)
    at eu.lunisolar.magma.func.supplier.LSupplier.tryGet(LSupplier.java:203)
    at tech.lnkd.editor.intellij.index.Extractor.indexByText(Extractor.java:70)
```

**Comment by lunisolar** [comment]
I will assume this happens when file disappears between being seen by IntelliJ and being actually indexed (build process). 
The only thing to do probably is just ignore FileNotFoundException instead of propagating the exception.

**Comment by lunisolar** [comment]
Fixed. Will be part of next release.
